#Hierarchical Clustering on Principle Components

#load packages
library(factoextra)
library(FactoMineR)
library(stats)
library(dplyr)
library(tidyr)

#load data
load(url("http://github.com/secanno/coralreef_stressorinteractions/blob/main/data.RData?raw=true"))
data_cover$Site <- NULL
str(data_cover)

#remove any columns with only 0
colSums(data_cover)
data_cover$PAD <- NULL
data_cover$SCH <- NULL
data_cover$AUD <- NULL

#convert to percent
data_cover <- data_cover*100

#remove data contributing <1% to dataset
colSums(data_cover)
ttl <- sum(colSums(data_cover))
dim(data_cover)

d_top <- data_cover[,colSums(data_cover) > (0.01*ttl)]

#compute PCA with ncp = 3 (to extract three dimensions)
res.pca <- PCA(d_top, ncp = 3, graph = TRUE)
plot(res.pca, choix = "varcor", ellipse = TRUE)
fviz_screeplot(res.pca)

#compute hierarchical clustering on principal components
res.hcpc <- HCPC(res.pca, graph = FALSE)

#visualize the dendrogram generated by the hierarchical clustering
fviz_dend(res.hcpc, cex = 1., palette = "aaas", rect = TRUE, rect_fill = TRUE,
          rect_border = "jco", labels_track_height = 0.8)

#visualize the individual sites on the PC map and color according to cluster

fviz_cluster(res.hcpc, repel = TRUE, show.cluster.cent = TRUE,
             palette = "jco", ggtheme = theme_minimal(), main = "Factor map")

#to display the original data with cluster assignments:
head(res.hcpc$data.clust, 10)

#to display quantitative variables that describe the most of each cluster:
res.hcpc$desc.var$quanti

#to show principal dimensions most associated with clusters
res.hcpc$desc.axes$quanti

#extract representative individuals of each cluster:
res.hcpc$desc.ind$para

